### PR TITLE
[DEPENDENCY]: upgraded to ember-cli@2.10

### PR DESCRIPTION
**Pull request by toranb**
Upgraded ember-cli and ember (in bower.json) to v2.10

### CODE REVIEW

**Comment by dustinfarris** [comment]
Travis is unhappy

**Comment by toranb** [comment]
@dustinfarris funny as I had this working locally :) will investigate tonight

**Comment by dbashford** [comment]
As part of this I'd suggest adding `2.10` to the [travis config](https://github.com/toranb/ember-redux/blob/master/.travis.yml#L16-L20).

**Comment by dbashford** [comment]
Builds for `2.0` and `2.4` are breaking, probably because `Ember.assign` was [introduced in 2.5](http://emberjs.com/blog/2016/04/11/ember-2-5-released.html#toc_changes-in-ember-2-5) and one of the changes is to move from `merge` to `assign`.

You could just flip back to `merge`. Or you could [polyfill it](https://github.com/shipshapecode/ember-assign-polyfill) for the purposes of running the tests.

**Comment by toranb** [comment]
@dustinfarris @dbashford updated ember-try to include 2.10 and fixed the ember.assign (my fault for adding that code -literally flipped to Object.assign a while back to avoid the 2.0 and 2.4 build failures #my_bad)

**Pull request merged**
