### PR TITLE
Update both ember and ember-cli to v2.9.1 

### PR DESCRIPTION
**Pull request by toranb**
Keeping up with the cool kids - the only huge jump I see is from `ember-cli-qunit v2.1.0 => v3`

This time it's just the bower/package.json/ember-cli updates :)

### CODE REVIEW

**Comment by toranb** [comment]
Interesting - suddenly after this update a handful of the first acceptance tests blow up in ember 2 and ember 2.4

**Comment by toranb** [comment]
looks like all that hacking of the array prototype w/ replace got the best of me :)

`ret.replace is not a function`

**Comment by toranb** [comment]
force pushed up a quick fix using splice -all is good now on both ember 2.4 and 2.9

**Comment by dustinfarris** [comment]
LGTM

**Pull request merged**
