### PR TITLE
[FEATURE]: return dispatch value to allow model hook to wait for thunk promises

### PR DESCRIPTION
**Pull request by brettburley**
When calling an action that returns a promise (ala redux-thunk), we must return that promise from the dispatch action so that we can use it in a model hook to take advantage of the Ember model loading hooks.

https://github.com/toranb/ember-redux/issues/5

### CODE REVIEW

**Comment by toranb** [comment]
This looks great! The only changes Id suggest before we pull this in

1) move the dynamic route out of the test and into the dummy app as a rea file 
2) remove the actions (loading) and use a real hbs each loop to confirm the users.all was setup correctly
3) add a link-to in the application.hbs file to /dynamic

I only considered asking for this change to help others who follow see a more consistent pattern of using the dummy app. I realize this isn't for everyone but I like having the ability to point at this addon and tell people who are less familiar with testing "just use ember s"

**Comment by brettburley** [comment]
Moved this route into the actual dummy app.

I did, however, keep the `loading` action in the route. This is invoked by Ember automatically when the route goes into a loading state, and I think it's important to catch this in this particular case. This is the part of the test that fails when the service's `dispatch` method *doesn't* return the promise. So by verifying that the loading state is invoked, we can be sure that we're properly returning a promise by the `dispatch` in the route's `model` hook.

I was unable to find a better way to determine if the route goes into a loading state... it's tough to catch in the acceptance test itself since any `andThen`s will wait for all promises to resolve (and therefore missing the loading substate completely).

**Comment by toranb** [comment]
@brettburley ah that makes total sense! Sorry for the lack of understanding on my part earlier!

This pull request looks solid my friend! Thanks for the extra work involved to educate people like me who are not as familiar w/ action creators yet :)

**Comment by toranb** [comment]
I'll merge this / bump the version, tag and publish it to npm tonight! Thanks again!

**Comment by toranb** [comment]
I just published this as `v1.3.0` on npm :) thanks again for all the hard work that went into this pull request!

**Pull request merged**
